# Site Settings
title: My Resume
url: 'http://crater.company'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: David Knapen
tagline: Geek aesthete
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I'm obsessed with painting color into text and making pictures tell the story. And I'm not afraid to use Google to find the most compelling way to do it. '

#sidebar links
email: david@crater.company
phone: 012 345 6789
website: crater.company #do not add http://
linkedin: david-knapen
github: croketephji
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
