# Site Settings
title: David Knapen's CV
url: 'http://crater.company'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: David Knapen
tagline: Aesthete geek humanitarian
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I want to be the bridge between people's stories and technology."

#sidebar links
email: davidknapen@gmail.com
phone: 00 972 59 537 93 27
whatsapp: 00 32 494 575 484
linkedin: david-knapen
github: croketephji
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development